[build]
  command = "gatsby build"
  publish = "public/"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://paradisedocs.netlify.com/*"
  to = "https://docs.paradisebots.net/:splat"
  status = 301
  force = true
